name: Frontend CI Pipeline

on:
  workflow_run:
    workflows: ["Backend CI Pipeline"]
    types:
      - completed

jobs:
  cypress-tests:
    runs-on: ubuntu-latest    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build and Serve Frontend
        run: |
          cd ui
          npm install
          npm run build
